[package]
name = "interliquid-sdk-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
interliquid-sdk = { path = ".." }
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
base64 = "0.21"
anyhow = "1.0" 